# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pokemons',
            new_name='pokemon',
        ),
    ]
